### ISSUE TITLE
Icon should follow Photon specs.

### ISSUE THREAD

**Issue by streetwolf** [MikkCZ/send-link-from-context-menu#1]
Icons for the new Photon GUI are basically black and white.  Your icon should follow the specs.  No more colored icons.  Your add-on works just fine.

**Comment by MikkCZ** [comment]
Thank you @streetwolf. I agree it makes sense for the coming Firefox 57. I can probably use http://design.firefox.com/icons/viewer/#mail to match the Photon as much as possible.
