### ISSUE TITLE
send-link-from-context-menu

### ISSUE THREAD

**Issue by MikeD4Wheeling** [MikkCZ/send-link-from-context-menu#14]
Not working using Win 10 and newest firefox browser.
I really like this right click add on BUT it has stopped working.
I see you want someone to take this add on over if I read this correctly.
I could not understand why Mozilla did not build this into their browser many moons ago. I was using something before this about 5-6 yrs ago and then your add-on came along and has been working perfect. I am sure there is a fix but my
thoughts are merge this into the product. The process is painless and efficient.
Plz advise___I would like my send link back of course.    Mike

**Comment by MikkCZ** [comment]
Please see #13 .
